

name: Update Json Menu
on:
  push:
  schedule:
    - cron:  '*/15 * * * *'
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.IFMCSRTEST }}  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: ðŸ” GH_TOKEN
        if: env.GH_TOKEN == ''
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "GH_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: main
        token: ${{ env.GH_TOKEN }}
    - name: Run PHP and Update Menu
      run: |
        cd php
        php index.php
        cd ../
    - name: Commit and push changes
      run: |-
        git diff
        git config user.name "ifm-csr"
        git config user.email "support.robotics@ifm.com"
        git diff --quiet || (git add -A && git commit -m "Updated with latest")
        git push
